package com.aode.buyoapp.LL.bean;

import java.util.Date;

/**
 * Created by 黄柏樟 on 2016/4/21.
 *
 * @Explain: 招聘信息实体类
 */
public class Recruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.content
     *
     * @mbggenerated
     */

    private String title;

    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.issuer
     *
     * @mbggenerated
     */
    private String issuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_recruit.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbggenerated
     */

    private Date date;

    public Recruit(Long id, String title, String content, String issuer, String phoneNumber, String address, Date date) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.issuer = issuer;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_recruit
     *
     * @mbggenerated
     */
    public Recruit() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.id
     *
     * @return the value of tb_recruit.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.id
     *
     * @param id the value for tb_recruit.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }


    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.address
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.content
     *
     * @return the value of tb_recruit.content
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.content
     *
     * @param content the value for tb_recruit.content
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.issuer
     *
     * @return the value of tb_recruit.issuer
     * @mbggenerated
     */
    public String getIssuer() {
        return issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.issuer
     *
     * @param issuer the value for tb_recruit.issuer
     * @mbggenerated
     */
    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.phone_number
     *
     * @return the value of tb_recruit.phone_number
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.phone_number
     *
     * @param phoneNumber the value for tb_recruit.phone_number
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_recruit.address
     *
     * @return the value of tb_recruit.address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_recruit.address
     *
     * @param address the value for tb_recruit.address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        return "Recruit{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", issuer='" + issuer + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", address='" + address + '\'' +
                ", date=" + date +
                '}';
    }
}